// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.product.domain;

import es.product.domain.StatusOperation;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StatusOperation_Roo_Configurable {
    
    declare @type: StatusOperation: @Configurable;
    
}
